name: CI - {{ project_name }}
on: [push, pull_request]

jobs:
  build-test-and-validate:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup vcpkg
        run: |
          git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
          $HOME/vcpkg/bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$HOME/vcpkg" >> $GITHUB_ENV
      
      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build gcc-13
      
      - name: Run Unit Tests
        run: |
          # Quick unit test validation with debug build
          cmake --preset debug
          cmake --build --preset debug
          ctest --preset debug --verbose
      
      - name: Run Comprehensive Downstream Compatibility Tests
        run: |
          # Comprehensive testing: Release/Debug × static/shared libraries
          # Validates downstream find_package() consumption
          chmod +x tests/test_downstream.sh
          ./tests/test_downstream.sh